CREATE TABLE CHECKINS (
   ID SERIAL PRIMARY KEY,
   NAME           TEXT    NOT NULL,
   PHONE_NUMBER   TEXT    NOT NULL,
   STATE          TEXT    NOT NULL  DEFAULT 'OPEN',
   CHECKED_IN_AT     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UPDATED_AT     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);