CREATE TABLE CHECKINS (
   ID BIGSERIAL PRIMARY KEY ,
   NAME           VARCHAR NOT NULL,
   PHONE_NUMBER   VARCHAR    NOT NULL,
   STATE          VARCHAR    NOT NULL  DEFAULT 'OPEN',
   CHECKED_IN_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UPDATED_AT     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);