CREATE TABLE CHECKINS (
   ID SERIAL PRIMARY KEY,
   NAME           VARCHAR(50) NOT NULL,
   PHONE_NUMBER   VARCHAR    NOT NULL,
   STATE          VARCHAR    NOT NULL  DEFAULT 'OPEN',
   CHECKED_IN_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UPDATED_AT     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO CHECKINS(NAME, PHONE_NUMBER) VALUES ('Varma', '9443322234');
INSERT INTO CHECKINS(NAME, PHONE_NUMBER) VALUES ('Raghu', '9443322235');