CREATE TABLE CHECKINS (
   ID SERIAL PRIMARY KEY,
   NAME           VARCHAR(50) NOT NULL,
   PHONE_NUMBER   VARCHAR    NOT NULL,
   STATE          VARCHAR    NOT NULL  DEFAULT 'OPEN',
   CHECKED_IN_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UPDATED_AT     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);